version: '3.9'
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: book_hub
      POSTGRES_PASSWORD: test_db_password
    ports:
      - '5432:5432'
    volumes:
      - book_hub_postgres:/var/lib/postgresql/data
  redis:
    image: redis:5.0.7
    ports:
      - '6379:6379'
    volumes:
      - book_hub_redis:/var/lib/redis/data
  book_hub:
    build:
      context: .
    volumes:
      - $PWD:/opt/app
    links:
      - postgres
      - redis
    ports:
      - '3000:3000'
    env_file:
      - .env
  sidekiq:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bundle exec sidekiq
    links:
      - redis
      - postgres
    env_file:
      - .env
  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    links:
      - book_hub
    ports:
      - '8020:8020'
volumes:
  book_hub_postgres:
  book_hub_redis:

